# Generated by Django 3.0.3 on 2020-03-05 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(max_length=255)),
                ('pet_name', models.CharField(max_length=255)),
                ('img_dir', models.ImageField(upload_to='uploads/%Y/%m/%d/')),
                ('rank', models.FloatField()),
            ],
        ),
    ]
